version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    steps:
      - run: echo

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            branches:
              only: /^dummy$/
