version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    steps:
      - checkout
      - run: go vet
      - run: go build -v
      - run: go test -v ./...

  release:
    docker:
      - image: circleci/golang:1.13.7
    steps:
      - checkout
      - run: go vet
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  all:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build
