version: 2.1
orbs:
  docker-buildx: sensu/docker-buildx@1.0.0
jobs:
  build:
    docker:
      - image: cimg/go:1.13
    steps:
      - run: mkdir -p ~/bin
      - run: echo 'export PATH="$HOME/bin:$PATH"' >> $BASH_ENV
      - run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b ~/bin v1.21.0
      - run: go get github.com/int128/goxzst
      - run: |
          curl -fL -o /tmp/ghcp.zip https://github.com/int128/ghcp/releases/download/v1.8.0/ghcp_linux_amd64.zip
          unzip /tmp/ghcp.zip -d ~/bin
      - checkout
      - run: make check
      - run: make dist
      - run: |
          if [ "$CIRCLE_TAG" ]; then
            make VERSION="$CIRCLE_TAG" release
          fi
      - persist_to_workspace:
          root: .
          paths:
            - docker
            - dist
  build_and_publish_docker_image:
    environment:
      DOCKER_BUILDKIT: 1
    machine:
      image: ubuntu-2004:202101-01
    steps:
      # - run: mkdir -p /tmp/workspace
      - attach_workspace:
          at: .
      - docker-buildx/install
      - run:
          name: Log in to docker hub
          command: |
            echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run: 
          name: Build and push tagged docker image
          command: |
            if [ "$CIRCLE_TAG" ]; then
              docker buildx build -t ${DOCKER_USER}/slack-docker:${CIRCLE_TAG} --push --platform linux/amd64,linux/arm64,linux/arm/v7 --build-arg VERSION=${CIRCLE_TAG} --build-arg GITHUB_USERNAME=${GITHUB_USERNAME} ./docker/
            fi

workflows:
  version: 2
  all:
    jobs:
      - build:
          context: open-source
          filters:
            tags:
              only: /.*/
      - build_and_publish_docker_image:
          context: open-source
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
          requires:
            - build