name: go

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*
  pull_request:
    paths:
      - .github/workflows/go.yaml
      - '**.go'
      - go.*

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: true
      - uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57.2
          args: --timeout=3m

  tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: true
      - run: go mod tidy
      - uses: int128/update-generated-files-action@v2

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
          cache: true
      - run: go test -v -race ./...
