name: release

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/release.yaml
      - '**.go'
      - go.*
    tags:
      - v*
  pull_request:
    paths:
      - .github/workflows/release.yaml
      - '**.go'
      - go.*

jobs:
  build:
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - runs-on: ubuntu-latest
            GOOS: linux
            GOARCH: arm64
          - runs-on: ubuntu-latest
            GOOS: linux
            GOARCH: arm
          - runs-on: ubuntu-latest
            GOOS: darwin
            GOARCH: amd64
          - runs-on: ubuntu-latest
            GOOS: darwin
            GOARCH: arm64
          - runs-on: ubuntu-latest
            GOOS: windows
            GOARCH: amd64
    runs-on: ${{ matrix.platform.runs-on }}
    env:
      GOOS: ${{ matrix.platform.GOOS }}
      GOARCH: ${{ matrix.platform.GOARCH }}
      CGO_ENABLED: 0
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.4
          cache: true
      - run: go build -ldflags '-X main.version=${{ github.ref_name }}'
      - uses: int128/go-actions/release@v1
        with:
          binary: slack-docker
